---
- name: Instalar dependencias y herramientas
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - byobu
    - emacs23-nox
    - python-pip
    - python-dev
    - libpq-dev
    - python-psycopg2
    - libjpeg62-dev 
    - libpng++-dev 
    - python-dev 
    - libxml2-dev 
    - libxslt1-dev 
    - libldap2-dev
    - libsasl2-dev 
    - libssl-dev
  tags:
    - packages

- name: Crear grupo Odoo del sistema
  group: name={{ system.odoo_group }} state=present
  tags: ['users','configuration']


- name: Crear usuario Odoo del sistema
  user: name={{ system.odoo_user }} generate_ssh_key=yes ssh_key_bits=2048 state=present
  tags: ['users','configuration']

- name: Crear directorios para sistema
  file: path=/home/{{ system.odoo_user }}/{{ odoo.home }} state=directory owner={{ system.odoo_user }} group={{ system.odoo_group }}
 