---
- name: Nginx | Instalar Nginx y Configurar como Web Proxy
  apt: pkg={{ item }} state=installed
  with_items:
    - nginx
  tags: ['configuration', 'webserver']

- name: Nginx | Crear conf proxy para odoo
  template:
    src: "templates/{{item}}.j2"
    dest: "{{nginx.etc_path}}/sites-available/odoo"
    owner: root
    group: root
    mode: 0755
  with_items: ['odoo']

- name: Nginx | Softlink para habilitar sitio
  file:
    src: "{{nginx.etc_path}}/sites-available/odoo"
    dest: "{{nginx.etc_path}}/sites-enabled/odoo"
    state: link

- name: Nginx | Asegurar que Nginx esta instalado (package)
  apt:
    pkg: nginx
    state: present
  notify:
    - restart nginx